/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.konan.blackboxtest;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Tag;
import org.jetbrains.kotlin.konan.blackboxtest.support.group.UseStandardTestCaseGroupProvider;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("native/native.tests/testData/lldb")
@TestDataPath("$PROJECT_ROOT")
@Tag("lldb")
@UseStandardTestCaseGroupProvider()
public class lldbShellTestGenerated extends AbstractNativeShellTest {
    @Test
    public void testAllFilesPresentInLldb() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("native/native.tests/testData/lldb"), Pattern.compile("^(.+)\\.shell$"), null, true);
    }

    @Test
    @TestMetadata("can_inspect_array_children.shell")
    public void testCan_inspect_array_children() throws Exception {
        runTest("native/native.tests/testData/lldb/can_inspect_array_children.shell");
    }

    @Test
    @TestMetadata("swift_with_kotlin_static_framework.shell")
    public void testSwift_with_kotlin_static_framework() throws Exception {
        runTest("native/native.tests/testData/lldb/swift_with_kotlin_static_framework.shell");
    }
}
